// WARNING: THIS FILE WAS AUTO GENERATED BY make_translation.py. PLEASE DO NOT EDIT.
 
/**
 * °F Fahrenheit Support
 * You will find the default Fahrenheit configuration in the translation_xx.json
 * If tempUnitFahrenheit is set to:
 *    true -  you can switch in menu settings to Fahrenheit or Celsius.
 *    false - you see only Celsius. All settings are then is in Celsius only.
 */

#ifndef _UNIT_H
#define _UNIT_H

  #ifdef LANG_EN
    #define  ENABLED_FAHRENHEIT_SUPPORT
  #endif /* ---- English ---- */

#endif /* _UNIT_H */
